In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer

# Load model and tokenizer
model = AutoModelForCausalLM.from_pretrained(
    "microsoft/Phi-3-mini-4k-instruct",
    device_map="cuda",
    torch_dtype="auto",
    trust_remote_code=False,
)
tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3-mini-4k-instruct")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/967 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.67G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/181 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/306 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/599 [00:00<?, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [ ]:
prompt = "Write an email apologizing to Sarah for the tragic gardening mishap. Explain how it happened.<|assistant|>"

input_ids = tokenizer(prompt, return_tensors="pt").input_ids.to("cuda")


generation_output = model.generate(
  input_ids=input_ids,
  max_new_tokens=100
)

print(tokenizer.decode(generation_output[0]))


Write an email apologizing to Sarah for the tragic gardening mishap. Explain how it happened.<|assistant|> Subject: Sincere Apologies for the Gardening Mishap


Dear Sarah,


I hope this message finds you well. I am writing to express my deepest apologies for the unfortunate incident that occurred in your garden yesterday.


As you know, I have always admired the beauty and tranquility of your garden. It was with great disappointment that I witnessed the accidental damage caused to your beloved rose bushes


In [ ]:
print(input_ids)

tensor([[14350,   385,  4876, 27746,  5281,   304, 19235,   363,   278, 25305,
           293, 16423,   292,   286,   728,   481, 29889, 12027,  7420,   920,
           372,  9559, 29889, 32001]], device='cuda:0')


In [ ]:
print(tokenizer.convert_ids_to_tokens(input_ids[0]))


['▁Write', '▁an', '▁email', '▁apolog', 'izing', '▁to', '▁Sarah', '▁for', '▁the', '▁trag', 'ic', '▁garden', 'ing', '▁m', 'ish', 'ap', '.', '▁Exp', 'lain', '▁how', '▁it', '▁happened', '.', '<|assistant|>']


In [ ]:
generation_output

tensor([[14350,   385,  4876, 27746,  5281,   304, 19235,   363,   278, 25305,
           293, 16423,   292,   286,   728,   481, 29889, 12027,  7420,   920,
           372,  9559, 29889, 32001,  3323,   622, 29901,   317,  3742,   406,
          6225, 11763,   363,   278, 19906,   292,   341,   728,   481,    13,
            13,    13, 29928,   799, 19235, 29892,    13,    13,    13, 29902,
          4966,   445,  2643, 14061,   366,  1532, 29889,   306,   626,  5007,
           304,  4653,   590,  6483,   342,  3095, 11763,   363,   278,   443,
          6477,   403, 15134,   393, 10761,   297,   596, 16423, 22600, 29889,
            13,    13,    13,  2887,   366,  1073, 29892,   306,   505,  2337,
          7336,  2859,   278, 15409,   322, 22024,   339,  1793,   310,   596,
         16423, 29889,   739,   471,   411,  2107, 23451,   358,   393,   306,
         16277,   287,   278, 11423,   284, 18658,  8581,   304,   596,  1339,
          8238, 11492, 27089,   267]], device='cuda:

In [ ]:
print(tokenizer.decode(29892))
print(tokenizer.decode(3323))

,
Sub


In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer

colors_list = [
    '102;194;165', '252;141;98', '141;160;203',
    '231;138;195', '166;216;84', '255;217;47'
]

def show_tokens(sentence, tokenizer_name):
    tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
    token_ids = tokenizer(sentence).input_ids
    for idx, t in enumerate(token_ids):
        print(
            f'\x1b[0;30;48;2;{colors_list[idx % len(colors_list)]}m' +
            tokenizer.decode(t) +
            '\x1b[0m',
            end=' '
        )

In [ ]:
text = """
MY SELF ADITYA SALUNKE # DATA SCIENCE STUDENT FROM MGM UNIVERSCITY
"""

In [ ]:
show_tokens(text, "bert-base-uncased")

[CLS] my self adi ##tya sal ##unk ##e # data science student from mgm un ##iver ##sc ##ity [SEP] 

In [ ]:
show_tokens(text,"gpt2")

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]


 MY  S ELF  AD ITY A  SAL UN KE  #  DATA  SC IENCE  STUD ENT  FROM  MGM  UNIVERS C ITY   
 

In [ ]:
show_tokens(text, "microsoft/Phi-3-mini-4k-instruct")

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


 
 MY SE L F AD ITY A S AL UN KE # D ATA S CI EN CE ST UD ENT FROM M GM UN I VER SC ITY  
 

In [ ]:

show_tokens(text, "facebook/galactica-1.3b")

tokenizer_config.json:   0%|          | 0.00/166 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/3.00 [00:00<?, ?B/s]


 MY  SEL F  AD ITY A  SAL UN KE   #  DATA  SCI ENCE  ST UD ENT  FROM  M GM  UN IVER SC ITY   
 

In [ ]:
# You need to request access before being able to use this tokenizer
show_tokens(text, "bigcode/starcoder2-15b")

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/958 [00:00<?, ?B/s]


 MY  S ELF  AD ITY A  SAL UN KE  #  DATA  S CI ENCE  ST UD ENT  FROM  M GM  UN IVER SC ITY  
 

In [ ]:
from transformers import AutoModel, AutoTokenizer
#load the tokenizer
tokenizer=AutoTokenizer.from_pretrained("microsoft/deberta-base")
#load the model
model=AutoModel.from_pretrained("microsoft/deberta-base")
# tokenizer the sentence
token=tokenizer(text,return_tensors="pt")
output=model(**token)[0]


In [ ]:
output.shape

torch.Size([1, 25, 768])

In [ ]:
for token in token['input_ids'][0]:
    print(tokenizer.decode(token))

[CLS]


MY
 S
ELF
 AD
ITY
A
 SAL
UN
KE
 #
 DATA
 SC
IENCE
 STUD
ENT
 FROM
 MGM
 UNIVERS
C
ITY
 


[SEP]


In [ ]:
output

tensor([[[ 0.0526, -0.0218, -0.0712,  ...,  0.0194,  0.0830, -0.0634],
         [-0.4430,  0.1052,  0.4444,  ...,  1.1173, -0.5213, -0.1435],
         [ 0.3090, -0.3543, -0.3062,  ...,  1.6468, -0.0342,  0.1421],
         ...,
         [-0.4439,  1.4771,  0.1948,  ...,  1.1166, -0.6193,  0.2979],
         [-0.0302, -0.1396,  0.3707,  ...,  0.3384, -0.6877,  1.3557],
         [ 0.2112,  0.0866, -0.1172,  ...,  0.0826,  0.2225,  0.0803]]],
       grad_fn=<AddBackward0>)

In [ ]:
from sentence_transformers import SentenceTransformer

# Load model
model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

# Convert text to text embeddings
vector = model.encode("Best movie ever!")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
vector.shape

(768,)

In [ ]:
import gensim.downloader as api

# Download embeddings (66MB, glove, trained on wikipedia, vector size: 50)
# Other options include "word2vec-google-news-300"
# More options at https://github.com/RaRe-Technologies/gensim-data
model = api.load("glove-wiki-gigaword-50")

[==================================================] 100.0% 66.0/66.0MB downloaded


In [ ]:
model.most_similar([model['king']], topn=11)

[('king', 1.0000001192092896),
 ('prince', 0.8236179351806641),
 ('queen', 0.7839043140411377),
 ('ii', 0.7746230363845825),
 ('emperor', 0.7736247777938843),
 ('son', 0.766719400882721),
 ('uncle', 0.7627150416374207),
 ('kingdom', 0.7542161345481873),
 ('throne', 0.7539914846420288),
 ('brother', 0.7492411136627197),
 ('ruler', 0.7434253692626953)]

Example on Token And Token Embedding

In [ ]:
from transformers import AutoTokenizer, AutoModel
import torch

# Load tokenizer and model (using bert-base-uncased for example)
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = AutoModel.from_pretrained("bert-base-uncased")

# Your input sentence
sentence = "I love cats!"

# Step 1: Tokenize the sentence
tokens = tokenizer.tokenize(sentence)
print("Tokens:", tokens)

# Step 2: Convert tokens to token IDs
token_ids = tokenizer.convert_tokens_to_ids(tokens)
print("Token IDs:", token_ids)

# Step 3: Get embeddings
# Tokenize with return_tensors='pt' to get input_ids as tensor
inputs = tokenizer(sentence, return_tensors="pt")

# Pass inputs to the model to get outputs (embeddings)
outputs = model(**inputs)

# The last hidden state is the embeddings for each token
embeddings = outputs.last_hidden_state  # shape: [batch_size, sequence_length, hidden_size]

print("Embeddings shape:", embeddings.shape)

# For example, embeddings for the first token (usually [CLS])
print("Embedding vector for first token (first 5 values):", embeddings[0,0,:5])


Tokens: ['i', 'love', 'cats', '!']
Token IDs: [1045, 2293, 8870, 999]
Embeddings shape: torch.Size([1, 6, 768])
Embedding vector for first token (first 5 values): tensor([ 0.0928,  0.3597,  0.0135, -0.3818, -0.2486], grad_fn=<SliceBackward0>)
